# Generated by Django 4.1.5 on 2023-01-22 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='BookingDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='Name',
            field=models.CharField(default='jmes', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='No_of_guests',
            field=models.IntegerField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='Inventory',
            field=models.IntegerField(default='4', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='Title',
            field=models.CharField(default='title', max_length=255),
            preserve_default=False,
        ),
    ]
